# Mod 06 Introducing `Series` Objects
>* Pandas 在異質數據的讀取、轉換和處理上，都讓分析人員更容易處理，例如：從`列欄試算表`中找到想要的值。
>* Pandas 提供兩種主要的資料結構，`Series 與 DataFrame`。Series 顧名思義就是用來處理序列相關的資料，主要為建立`索引的一維陣列`。DataFrame (excel表)則是用來處理結構化(Table like)的資料，有`列 row 索引與欄 column 標籤`的二維資料集，例如關聯式資料庫、CSV 等等。(如果是datafrme ，即使看到的資料只有一行，一樣是二維資料)
>* 透過載入至 Pandas 的資料結構物件後，可以透過結構化物件所提供的方法，來快速地進行`資料的前處理`，如資料補值，空值去除或取代......等。
>* 更多的輸入來源及輸出整合性，例如：可以從`資料庫讀取資料進入` Dataframe，也可將處理完的資料`存回資料庫`。

>><img src="./img/pandasDF02.png"  style='width:100%'>
>><img src="./img/pandasDF01.png"  style='width:100%'>

In [2]:
import numpy as np
import pandas as pd
np.__version__, pd.__version__

('2.3.5', '2.3.3')

## 6-1 The Pandas Series Object
> ### list vs. array vs. Series : `array like`
> >><img src="./img/series01.png"  style='width:80%'>

In [3]:
# float
lst1 = [0.25, 0.5, -0.75, 1]      # list
np_array = np.array(lst1)         # array,    try reshape

ser1 = pd.Series(lst1)            # list to series
ser2 = pd.Series(np_array)        # array to series

print(f'lst1\t\t= {lst1}\n'
      f'np_array\t= {np_array}\n\n'
      f'ser1 =\n{ser1}\n\n'
      f'type(ser1) : {type(ser1)}\n\n'
      f'ser2 =\n{ser2}')

lst1		= [0.25, 0.5, -0.75, 1]
np_array	= [ 0.25  0.5  -0.75  1.  ]

ser1 =
0    0.25
1    0.50
2   -0.75
3    1.00
dtype: float64

type(ser1) : <class 'pandas.core.series.Series'>

ser2 =
0    0.25
1    0.50
2   -0.75
3    1.00
dtype: float64

## 6-2 boolean / logical & arithmetic operation

In [4]:
print(f'ser1 =\n{ser1}\n\n'
      f'ser1[ser1>0] =\n{ser1[ser1>0]}\n\n'
      f'ser1*2 =\n{ser1*2}\n\n'
      f'np.exp(ser1) =\n{np.exp(ser1)}')

ser1 =
0    0.25
1    0.50
2   -0.75
3    1.00
dtype: float64

ser1[ser1>0] =
0    0.25
1    0.50
3    1.00
dtype: float64

ser1*2 =
0    0.5
1    1.0
2   -1.5
3    2.0
dtype: float64

np.exp(ser1) =
0    1.284025
1    1.648721
2    0.472367
3    2.718282
dtype: float64

## 6-3 成員運算子(Membership Operators)

In [5]:
print(f'{ser1}\n\n'
      f'2 in ser1\t: {2 in ser1}\n'     # 2 is index, not value
      f'0.5 in ser1\t: {0.5 in ser1}')  # 1, 2 are indexes, not values

0    0.25
1    0.50
2   -0.75
3    1.00
dtype: float64

2 in ser1	: True
0.5 in ser1	: False

### dtype : object

In [6]:
ser1 = pd.Series([0.25, 0.5, 'hello', 1.0])  # dtype : object
ser1, print(ser1)

0     0.25
1      0.5
2    hello
3      1.0
dtype: object

(0     0.25
 1      0.5
 2    hello
 3      1.0
 dtype: object,
 None)

## 6-4 `Series` as generalized `NumPy array`
### index

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'c', 'b', 'd'])
# data = pd.Series([0.25, 0.5, 0.75, 1.0], index=list('acbd'))         # series 可以 index
data_np = np.array([0.25, 0.5, 0.75, 1.0])
print(f'data =\n{data}\n\n'
      f'data_np\t\t= {data_np}\n'
      f"data['b']\t= {data['b']}\n"
      f"data_np[2]\t= {data_np[2]}\n")

data =
a    0.25
c    0.50
b    0.75
d    1.00
dtype: float64

data_np		= [0.25 0.5  0.75 1.  ]
data['b']	= 0.75
data_np[2]	= 0.75

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])   # index by numbers(str)
print(f'data =\n{data}\n\n'
      f'data[5] = {data[5]}')  # index代表 key like dictionary

data =
2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

data[5] = 0.5

## 6-5 dict. to Series (key as index)

In [9]:
data = pd.Series({'A':'apple', 'B':'banana', 'C':'cherry'}) # like dictionary特殊化的字典, 但是它可支援陣列的運算 like slice
print(f"{data}\n\n"
      f"{data['A':'B']}")

A     apple
B    banana
C    cherry
dtype: object

A     apple
B    banana
dtype: object

### `Series` as specialized `dictionary`

In [10]:
population_dict = {'California': 38332521, 'Texas': 26448193,     # a dictionary
                   'New York': 19651127, 'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### like dictionary

In [11]:
population['California'], population_dict['California']

(np.int64(38332521), 38332521)

### slice : not for dict

In [12]:
print(f'{population}\n\n'
      f"{population['California':'New York']}")
# population.loc['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

California    38332521
Texas         26448193
New York      19651127
dtype: int64

## 6-6 Series Attributes

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(f'data =\n{data}\n\n'
      f'data.values\t= {data.values}\n'
      f'data.index\t= {data.index}\n'
      f'data.shape\t= {data.shape}\n'
      f'data.ndim\t= {data.ndim}\n'
      f'data.dtypes\t= {data.dtypes}\n'
      f'data.size\t= {data.size}\n'
      f'data.nbytes\t= {data.nbytes}')

data =
0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

data.values	= [0.25 0.5  0.75 1.  ]
data.index	= RangeIndex(start=0, stop=4, step=1)
data.shape	= (4,)
data.ndim	= 1
data.dtypes	= float64
data.size	= 4
data.nbytes	= 32

### index vs slice

In [14]:
print(f'data\t=\n{data}\n\n'
      f'data[1]\t= {data[1]}\n\n'
      f'data[1:3] =\n{data[1:3]}')

data	=
0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

data[1]	= 0.5

data[1:3] =
1    0.50
2    0.75
dtype: float64

### Axis Indexes with Duplicate Labels

In [15]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c']) # index 可重複 no unique

# get all objects with index 'a'
print(f"{obj}\n\n{obj['a']}")

a    0
a    1
b    2
b    3
c    4
dtype: int64

a    0
a    1
dtype: int64

### index.is_unique

In [16]:
# Check if index is unique
obj.index.is_unique  # it is attribut, don't need ()

False

### Series name : column name in df
如果用於生成 DataFrame，則 Series 的名稱將成為其索引或列名稱。每當使用解釋器顯示 Series 時，也會使用它。

In [18]:
# Change Series name
data = pd.Series([0.25, 0.5, 0.75, 1.0, None, np.nan])
data.name = 'myseries' #你的屬性叫做myserios->欄位名稱
data, pd.DataFrame(data), pd.DataFrame(data).columns #reshape轉成2維的概念

(0    0.25
 1    0.50
 2    0.75
 3    1.00
 4     NaN
 5     NaN
 Name: myseries, dtype: float64,
    myseries
 0      0.25
 1      0.50
 2      0.75
 3      1.00
 4       NaN
 5       NaN,
 Index(['myseries'], dtype='object'))

## 6-7 loc 是 key, iloc 是 intgrate-location(整數位置)
>### loc - `label` indexing 標籤索引 (標籤用)
>### iloc - `positional` indexing 位置索引 (一定是 int 整數用)
>><img src="./img/loc_iloc.jpg"  style='width:100%'>

### loc

In [23]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

print(f'{data}\n\n'
      f'{data.loc[3]}\n\n' 
      f'{data[1:3]}\n\n'   # position index 沒寫就是iloc -->不含3(不含終點)
      f'{data.loc[1:3]}') # 包含 3(終點會跑出來)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

1.0

1    0.50
2    0.75
dtype: float64

1    0.50
2    0.75
3    1.00
dtype: float64

### iloc

In [ ]:
print(f'{data}\n\n'
      f'{data.iloc[3]}\n\n'
      f'{data[1:3]}\n\n'
      f'{data.iloc[1:3]}') # 不包含 3

### index=['5','4','3','2']

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['5','4','3','2'])
print(f"{data}\n\n"
      f"{data.loc['3']}\n\n"
      f"{data['3':'5':-1]}\n\n"
      f"{data.loc['5':'3']}") # include 3

### iloc

In [ ]:
print(f'{data}\n\n'
      f'{data.iloc[3]}\n\n'
      f'{data.iloc[1:3]}') # 不包含 3

### `iloc` 屬性允許進行索引和切片，它是引用 `隱式` Python 風格的索引：
>><img src="./img/iloc01.png"  style='width:100%'>

In [24]:
data = pd.Series(['a','b','c'], index=[1,3,5] )
print(f'{data}\n\n'
      f'{data.iloc[1]}\n')

1    a
3    b
5    c
dtype: object

b

In [25]:
print(f'{data}\n\n'
      f'{data[1:3]}\n\n'
      f'{data.loc[1:3]}\n\n'
      f'{data.iloc[1:3]}') # 位置  slice

1    a
3    b
5    c
dtype: object

3    b
5    c
dtype: object

1    a
3    b
dtype: object

3    b
5    c
dtype: object

# `練習 Q02 (1,2)`

---

# Mod 07 Getting Started with pandas

In [ ]:
import pandas as pd
# from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt

## 7-1 DataFrame
>Pandas 是 Python 進行資料處理和資料分析一個好用的工具，其主要資料結構有包含：`Series 物件和 DataFrame 物件`。其中 DataFrame 就類似我們在使用的 `Excel 試算表`一樣，由欄列所組成的表格結構。由於 Pandas 本身基於 Numpy 所以在使用大量資料運算時效能表現也優於原生的 Python 資料結構，所以是常用將資料載入進行資料分析的好用工具。

>> * Series 物件 : Series 為索引標籤和實際值的陣列組合
>> * DataFrame 物件 : DataFrame 類似試算表和關聯式資料庫資料表（table）欄列結構，每一欄是`固定資料型別`但不同欄可以儲存不同的資料型別

> 1. 就如 Table 表格,  多個 series, 共享相同的 index, 每個 series 可以不同的 Data Type
> 2. `列索引與欄索引`  [row_indexer , col_indexer]  (列標籤索引與欄標籤索引)
> 3. axis 方向很重要 
><img src="./img/pandasDF.png"  style='width:100%'>
><img src="./img/pandasDF03.png"  style='width:100%'>

In [31]:
# it is a dictionary
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],     # dictionary
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'popu': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
print(f"data :\n{data}\n\n"
      f"data['state'] : {data['state']}\n\n"
      f"{pd.DataFrame(data)}")
pd.DataFrame(data)['state'], pd.Series(data)

data :
{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'popu': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

data['state'] : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada']

    state  year  popu
0    Ohio  2000   1.5
1    Ohio  2001   1.7
2    Ohio  2002   3.6
3  Nevada  2001   2.4
4  Nevada  2002   2.9
5  Nevada  2003   3.2

(0      Ohio
 1      Ohio
 2      Ohio
 3    Nevada
 4    Nevada
 5    Nevada
 Name: state, dtype: object,
 state    [Ohio, Ohio, Ohio, Nevada, Nevada, Nevada]
 year           [2000, 2001, 2002, 2001, 2002, 2003]
 popu                 [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
 dtype: object)

### df, df.T

In [33]:
df = pd.DataFrame(data, index=['d','f','f','h','j','k'])
print(f'{df}\n\n{df.T}') #轉置

    state  year  popu
d    Ohio  2000   1.5
f    Ohio  2001   1.7
f    Ohio  2002   3.6
h  Nevada  2001   2.4
j  Nevada  2002   2.9
k  Nevada  2003   3.2

          d     f     f       h       j       k
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
year   2000  2001  2002    2001    2002    2003
popu    1.5   1.7   3.6     2.4     2.9     3.2

### attributes

In [34]:
print(f'df :\n{df}\n\n'
      f'df.index\t= {df.index}\n'
      f'df.columns\t= {df.columns}\n\n'
      f'df.values =\n{df.values}\n\n'
      f'type(df.values)\t= {type(df.values)}\n'
      f'df.ndim\t\t= {df.ndim}\n'
      f'df.shape\t= {df.shape}')

df :
    state  year  popu
d    Ohio  2000   1.5
f    Ohio  2001   1.7
f    Ohio  2002   3.6
h  Nevada  2001   2.4
j  Nevada  2002   2.9
k  Nevada  2003   3.2

df.index	= Index(['d', 'f', 'f', 'h', 'j', 'k'], dtype='object')
df.columns	= Index(['state', 'year', 'popu'], dtype='object')

df.values =
[['Ohio' 2000 1.5]
 ['Ohio' 2001 1.7]
 ['Ohio' 2002 3.6]
 ['Nevada' 2001 2.4]
 ['Nevada' 2002 2.9]
 ['Nevada' 2003 3.2]]

type(df.values)	= <class 'numpy.ndarray'>
df.ndim		= 2
df.shape	= (6, 3)

### df observations

In [40]:
print(f'df :\n{df}\n\n'
      f'df.describe() :\n{df.describe()} end\n\n'  # state 不見了, why?  只對數字進行描述
      f'df.info :\n{df.info()}\n\n' #第一個跑出來 如果有非數字跟空值->dtype會是obj
      f'df.head(4) :\n{df.head(4)}\n\n'    # default top 5 rows
      f'df.tail(4) :\n{df.tail(4)}\n')

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, d to k
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   6 non-null      object
 1   year    6 non-null      int64
 2   popu    6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 364.0+ bytes
df :
    state  year  popu
d    Ohio  2000   1.5
f    Ohio  2001   1.7
f    Ohio  2002   3.6
h  Nevada  2001   2.4
j  Nevada  2002   2.9
k  Nevada  2003   3.2

df.describe() :
              year      popu
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000 end

df.info :
None

df.head(4) :
    state  year  popu
d    Ohio  2000   1.5
f    Ohio  2001   1.7
f    Ohio  2002   3.6
h  Nevada  2001   2.4

df.tail(4) :
    state  year  popu
f    Ohio  2002   3.6
h  Nevada  2001   2.4
j  Nevada  2002   2.9
k  Nevada  2003   3.2

### columns edit

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],     # dictionary
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'popu': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

pd.DataFrame(data, columns=['year', 'state', 'popu', 'nothing'])  # column 排列 add new column 'nothing'

   year   state  popu nothing
0  2000    Ohio   1.5     NaN
1  2001    Ohio   1.7     NaN
2  2002    Ohio   3.6     NaN
3  2001  Nevada   2.4     NaN
4  2002  Nevada   2.9     NaN
5  2003  Nevada   3.2     NaN

### df = Series + Series

In [38]:
area = pd.Series({'California': 423967, 'New York': 141297,'Texas': 695662,
                  'Florida': 170312, 'Illinois': 149995})
popu = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'popu':popu})

print(f'data :\n{data}\n\n'
      f'data.area :\n{data.area}\n\n'
      f"data['area'] :\n{data['area']}\n\n"
      f'data.popu :\n{data.popu}\n\n'
      f"data['popu'] :\n{data['popu']}")
type(data['popu'])

data :
              area      popu
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

data.area :
California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

data['area'] :
California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

data.popu :
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
Name: popu, dtype: int64

data['popu'] :
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
Name: popu, dtype: int64

pandas.core.series.Series

### new column

In [39]:
data['density'] = data['popu'] / data['area']
data.density = data.popu / data.area     # same
data

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

### passing a single "index" to a ``DataFrame`` accesses a column:
### `a Sereis`

In [45]:
print(f"data['area'] :\n{data['area']}\n\n"
      f"data.area :\n{data.area}\n\n"
      f"data.area.ndim\t: {data.area.ndim}\n\n" #維度 這裡只有1維
      f"type(data.area)\t: {type(data.area)}")   # Series

data['area'] :
California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

data.area :
California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

data.area.ndim	: 1

type(data.area)	: <class 'pandas.core.series.Series'>

### `a DataFrame`

In [47]:
print(f"{data[['area']]}\n\n" #用兩個中括弧 把它變成dataframe
      f"data[['area']].ndim : {data[['area']].ndim}\n\n" #變2維了
      f"{type(data[['area']])}")    # DataFream

              area
California  423967
Florida     170312
Illinois    149995
New York    141297
Texas       695662

data[['area']].ndim : 2

<class 'pandas.core.frame.DataFrame'>

### DataFrame 可 rename index & column name (Series 不能改變 index)

In [48]:
data1 = data.rename(columns={'area': 'Col_1'}, index={'California': 'Row_1'})
print(f'data :\n{data}\n\n'
      f'data rename data1 = \n{data1}')

data :
              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

data rename data1 =
           Col_1      popu     density
Row_1     423967  38332521   90.413926
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
New York  141297  19651127  139.076746
Texas     695662  26448193   38.018740

## 7-2 df slice

### ``loc`` indexer slice

In [49]:
print(f'{data}\n\n'
      f"{data.loc['California':'New York',['area','density']]}\n")  # fancy index

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

              area     density
California  423967   90.413926
Florida     170312  114.806121
Illinois    149995   85.883763
New York    141297  139.076746

In [50]:
data.loc['California':'New York','area':'density':2]  # slice (faster) skip 'popu'

              area     density
California  423967   90.413926
Florida     170312  114.806121
Illinois    149995   85.883763
New York    141297  139.076746

In [51]:
print(f'{data}\n\n'
      f"{data.loc['Texas']}")

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

area       6.956620e+05
popu       2.644819e+07
density    3.801874e+01
Name: Texas, dtype: float64

In [56]:
data.loc['Illinois', 'popu']

np.int64(12882135)

In [53]:
print(f'{data}\n\n'
      f"{data.loc[:'Texas', :'popu']}")   # 終點要算

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

              area      popu
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

### 2d ``iloc`` indexer slice

In [54]:
print(f'data :\n{data}\n\n'
      f'data.iloc[1:4,[0,2]] :\n{data.iloc[1:4,[0,2]]}\n\n'      # fancy index
      f'data.iloc[1:4,::2] :\n{data.iloc[1:4,::2]}')   # silce (faster)

data :
              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

data.iloc[1:4,[0,2]] :
            area     density
Florida   170312  114.806121
Illinois  149995   85.883763
New York  141297  139.076746

data.iloc[1:4,::2] :
            area     density
Florida   170312  114.806121
Illinois  149995   85.883763
New York  141297  139.076746

In [57]:
print(f'{data}\n\n'
      f'{data.iloc[0]}\n')  # row 0

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

area       4.239670e+05
popu       3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [58]:
print(f'{data}\n\n'
      f'{data.iloc[:3, :2]}')

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

              area      popu
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [59]:
print(f'{data}\n\n'
      f'{data.iloc[1, 2]}')  # [row, column]

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

114.80612053173

### combine masking & fancy indexing

In [60]:
print(f'{data}\n\n'
      f"{data.loc[data.density>100, ['popu', 'density']]}\n\n"
      f"{data.loc[data['density']>100, ['popu', 'density']]}\n\n"    # same as above
      f"{data.loc[data.density>100, 'popu':'density']}")          # same as above

              area      popu     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

              popu     density
Florida   19552860  114.806121
New York  19651127  139.076746

              popu     density
Florida   19552860  114.806121
New York  19651127  139.076746

              popu     density
Florida   19552860  114.806121
New York  19651127  139.076746

## 7-3 random sample : rows or [columns]
> DataFrame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)

In [62]:
# s1 = pd.Series(range(10, 15), ind_char)
s1 = pd.DataFrame(np.arange(50).reshape(-1, 5),  
                   columns=['Ohio', 'Texas', 'California', 'illinos', 'New York'])
print(s1, '\n')
s1['New York']=s1['New York'].apply(lambda x:1 if x<25 else 2)
s1

   Ohio  Texas  California  illinos  New York
0     0      1           2        3         4
1     5      6           7        8         9
2    10     11          12       13        14
3    15     16          17       18        19
4    20     21          22       23        24
5    25     26          27       28        29
6    30     31          32       33        34
7    35     36          37       38        39
8    40     41          42       43        44
9    45     46          47       48        49

   Ohio  Texas  California  illinos  New York
0     0      1           2        3         1
1     5      6           7        8         1
2    10     11          12       13         1
3    15     16          17       18         1
4    20     21          22       23         1
5    25     26          27       28         2
6    30     31          32       33         2
7    35     36          37       38         2
8    40     41          42       43         2
9    45     46          47       48         2

### replace = True : 抽樣完放回

In [66]:
print(f'frac=.6 :\n{s1.sample(frac=.6)}\n\n'   # replace =1, replace = False 抽樣60%
      f'n=5, axis=0, replace=True, random_state=2 :\n{s1.sample(n=5, axis=0, replace=True, random_state=2)}\n\n'
      #抽樣5筆 0軸 可重複 亂數固定
      f'frac=.6, axis=1 :\n{s1.sample(frac=.6, axis=1)}\n\n'
      # 僅水平抽60%
      f'frac=2, replace=True :\n{s1.sample(frac=2, replace=True)}')   # frac =2, replace=True  
      #抽200% 可重複

frac=.6 :
   Ohio  Texas  California  illinos  New York
3    15     16          17       18         1
8    40     41          42       43         2
4    20     21          22       23         1
6    30     31          32       33         2
5    25     26          27       28         2
9    45     46          47       48         2

n=5, axis=0, replace=True, random_state=2 :
   Ohio  Texas  California  illinos  New York
8    40     41          42       43         2
8    40     41          42       43         2
6    30     31          32       33         2
2    10     11          12       13         1
8    40     41          42       43         2

frac=.6, axis=1 :
   illinos  New York  California
0        3         1           2
1        8         1           7
2       13         1          12
3       18         1          17
4       23         1          22
5       28         2          27
6       33         2          32
7       38         2          37
8       43         2          42
9       48         2          47

frac=2, replace=True :
   Ohio  Texas  California  illinos  New York
3    15     16          17       18         1
7    35     36          37       38         2
4    20     21          22       23         1
1     5      6           7        8         1
1     5      6           7        8         1
9    45     46          47       48         2
0     0      1           2        3         1
1     5      6           7        8         1
7    35     36          37       38         2
7    35     36          37       38         2
4    20     21          22       23         1
3    15     16          17       18         1
4    20     21          22       23         1
2    10     11          12       13         1
5    25     26          27       28         2
2    10     11          12       13         1
1     5      6           7        8         1
6    30     31          32       33         2
0     0      1           2        3         1
6    30     31          32       33         2

### build train and test sets

In [67]:
train = s1.sample(frac=.7) #抽七成
test = s1.drop(train.index) #然後把他刪掉
print(f's1 :\n{s1}\n\n'
      f'train :\n{train}\n\n'
      f'test :\n{test}')

s1 :
   Ohio  Texas  California  illinos  New York
0     0      1           2        3         1
1     5      6           7        8         1
2    10     11          12       13         1
3    15     16          17       18         1
4    20     21          22       23         1
5    25     26          27       28         2
6    30     31          32       33         2
7    35     36          37       38         2
8    40     41          42       43         2
9    45     46          47       48         2

train :
   Ohio  Texas  California  illinos  New York
7    35     36          37       38         2
6    30     31          32       33         2
9    45     46          47       48         2
5    25     26          27       28         2
3    15     16          17       18         1
2    10     11          12       13         1
4    20     21          22       23         1

test :
   Ohio  Texas  California  illinos  New York
0     0      1           2        3         1
1     5      6           7        8         1
8    40     41          42       43         2

### sklearn.model_selection.train_test_split
><img src="./img/stratified.png"  style='width:100%'>

In [68]:
from sklearn.model_selection import train_test_split
y = s1['New York']
# s1.drop(['New York'],axis=1, inplace=True)
X_train, X_test, y_train, y_test = train_test_split(s1.iloc[:,:-1], y, test_size=0.3, 
                                                    random_state=None, stratify=y)  # stratify
print(f'X_train :\n{X_train}\n\n'
      f'y_train :\n{y_train}\n\n'
      f'X_test :\n{X_test}\n\n'
      f'y_test :\n{y_test}')

X_train :
   Ohio  Texas  California  illinos
5    25     26          27       28
8    40     41          42       43
4    20     21          22       23
9    45     46          47       48
6    30     31          32       33
1     5      6           7        8
2    10     11          12       13

y_train :
5    2
8    2
4    1
9    2
6    2
1    1
2    1
Name: New York, dtype: int64

X_test :
   Ohio  Texas  California  illinos
0     0      1           2        3
7    35     36          37       38
3    15     16          17       18

y_test :
0    1
7    2
3    1
Name: New York, dtype: int64

---

# Mod 08 Essential Functionality
><img src="./img/func.jpg" style='width:100%'>

## 8-1 Reindexing

In [69]:
import pandas as pd
import numpy as np
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [71]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])  # e NaN 順序調整
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

### reindex, ffill/ bfill

In [73]:
obj3 = pd.Series(['blue', 'purple', 'yellow', 'red'], index=[0, 2, 3, 5])
print(f"obj3 :\n{obj3}\n\n"
      f"obj3.reindex(range(10), method='ffill' :\n{obj3.reindex(range(10), method='ffill')}\n\n"  
      # f-fill 空值會抓上面資料 
      f"obj3.reindex(range(10), method='bfill' :\n{obj3.reindex(range(10), method='bfill')}\n")
      # b-fill 空值抓下面的資料

obj3 :
0      blue
2    purple
3    yellow
5       red
dtype: object

obj3.reindex(range(10), method='ffill' :
0      blue
1      blue
2    purple
3    yellow
4    yellow
5       red
6       red
7       red
8       red
9       red
dtype: object

obj3.reindex(range(10), method='bfill' :
0      blue
1    purple
2    purple
3    yellow
4       red
5       red
6       NaN
7       NaN
8       NaN
9       NaN
dtype: object

### reindex NaN

In [74]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame2 = frame.reindex(['a', 'b', 'c', 'd'])    # row reindex
print(f'frame :\n{frame}\n\n'
      f'frame2 :\n{frame2}')

frame :
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

frame2 :
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [75]:
states = ['Texas', 'Utah', 'California']
frame, frame.reindex(columns=states)

(   Ohio  Texas  California
 a     0      1           2
 c     3      4           5
 d     6      7           8,
    Texas  Utah  California
 a      1   NaN           2
 c      4   NaN           5
 d      7   NaN           8)

### Indexing with a DataFrame's columns

In [76]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [78]:
frame2 = frame.set_index(['c'])  # drop c 把他欄變成index
frame2

     a  b  d
c
one  0  7  0
one  1  6  1
one  2  5  2
two  3  4  0
two  4  3  1
two  5  2  2
two  6  1  3

In [90]:
frame.set_index(['c'], drop=False)  # don't drop column c C欄位還在
# inplae  true C欄位刪除

     a  b    c  d
c
one  0  7  one  0
one  1  6  one  1
one  2  5  one  2
two  3  4  two  0
two  4  3  two  1
two  5  2  two  2
two  6  1  two  3

In [85]:
frame2.reset_index()  # back to original 重啟

     c  a  b  d
0  one  0  7  0
1  one  1  6  1
2  one  2  5  2
3  two  3  4  0
4  two  4  3  1
5  two  5  2  2
6  two  6  1  3

## 8-2 Dropping Entries from an Axis
> axis : {0 or 'index', 1 or 'columns'}<br>
> default 0<br>
> Whether to drop labels from the index (0 or 'index') or columns (1 or 'columns').

### drop inplace = False

In [86]:
import pandas as pd
import numpy as np
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [89]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(f"{obj}\n\n"
      f"{obj.drop('c')}\n\n" 
      f"{obj.drop(['d', 'c'])}\n\n"
      f"{obj}")   # no inplace 不會直接修改原始資料

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

### drop inplace = True

In [91]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj, '\n')
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [92]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### inplace = False / True

In [93]:
data.drop(['Colorado', 'Ohio'], inplace=False), data

(          one  two  three  four
 Utah        8    9     10    11
 New York   12   13     14    15,
           one  two  three  four
 Ohio        0    1      2     3
 Colorado    4    5      6     7
 Utah        8    9     10    11
 New York   12   13     14    15)

In [94]:
data.drop('two', axis=1), data.drop(['two', 'four'], axis='columns')

(          one  three  four
 Ohio        0      2     3
 Colorado    4      6     7
 Utah        8     10    11
 New York   12     14    15,
           one  three
 Ohio        0      2
 Colorado    4      6
 Utah        8     10
 New York   12     14)

## 8-3 Arithmetic and Data Alignment

In [95]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [97]:
df1 + df2 #欄列名稱相同才可相加

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [98]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1, df2

(     a    b     c     d
 0  0.0  1.0   2.0   3.0
 1  4.0  5.0   6.0   7.0
 2  8.0  9.0  10.0  11.0,
       a     b     c     d     e
 0   0.0   1.0   2.0   3.0   4.0
 1   5.0   NaN   7.0   8.0   9.0
 2  10.0  11.0  12.0  13.0  14.0
 3  15.0  16.0  17.0  18.0  19.0)

In [100]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

## 8-4 Function Application and Mapping

In [101]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame, np.abs(frame), np.abs(frame.b)

(               b         d         e
 Utah    0.877756 -0.572436  1.318622
 Ohio    0.739379 -0.898489 -0.249900
 Texas   1.546597 -0.576437 -1.053655
 Oregon -1.665173  0.099351 -0.345374,
                b         d         e
 Utah    0.877756  0.572436  1.318622
 Ohio    0.739379  0.898489  0.249900
 Texas   1.546597  0.576437  1.053655
 Oregon  1.665173  0.099351  0.345374,
 Utah      0.877756
 Ohio      0.739379
 Texas     1.546597
 Oregon    1.665173
 Name: b, dtype: float64)

### apply (default row axis=0)

In [102]:
# frame, frame.apply(np.cumsum)
print(frame, '\n\n', frame.b.apply(lambda x: x+10),'\n\n')

               b         d         e
Utah    0.877756 -0.572436  1.318622
Ohio    0.739379 -0.898489 -0.249900
Texas   1.546597 -0.576437 -1.053655
Oregon -1.665173  0.099351 -0.345374

 Utah      10.877756
Ohio      10.739379
Texas     11.546597
Oregon     8.334827
Name: b, dtype: float64

### Sorting and Ranking

In [104]:
obj = pd.Series(range(4), index=['D', 'a', 'c', 'b'])
obj, obj.sort_index() #以ASCII排列

(D    0
 a    1
 c    2
 b    3
 dtype: int64,
 D    0
 a    1
 b    3
 c    2
 dtype: int64)

In [107]:
frame = pd.DataFrame(np.arange(12).reshape((3, 4)),
                     index=['three', 'one', 'four'],
                     columns=['d', 'a', 'b', 'c'])
print(f'{frame}\n\n'
      f'{frame.sort_index()}\n\n' #以開頭第一字母排序
      f'{frame.sort_index(axis=1)}\n\n'
      f'{frame.sort_index().sort_index(axis=1)}')

       d  a   b   c
three  0  1   2   3
one    4  5   6   7
four   8  9  10  11

       d  a   b   c
four   8  9  10  11
one    4  5   6   7
three  0  1   2   3

       a   b   c  d
three  1   2   3  0
one    5   6   7  4
four   9  10  11  8

       a   b   c  d
four   9  10  11  8
one    5   6   7  4
three  1   2   3  0

In [109]:
 frame, frame.sort_index(axis=1, ascending=False) #由大到小

(       d  a   b   c
 three  0  1   2   3
 one    4  5   6   7
 four   8  9  10  11,
        d   c   b  a
 three  0   3   2  1
 one    4   7   6  5
 four   8  11  10  9)

In [110]:
obj = pd.Series([4, 7, -3, 2])
obj, obj.sort_values()

(0    4
 1    7
 2   -3
 3    2
 dtype: int64,
 2   -3
 3    2
 0    4
 1    7
 dtype: int64)

In [112]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2]) #空值排最後
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [113]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame, frame.sort_values(by='b') # by column 'b'

(   b  a
 0  4  0
 1  7  1
 2 -3  0
 3  2  1,
    b  a
 2 -3  0
 3  2  1
 0  4  0
 1  7  1)

In [114]:
frame.sort_values(by=['a', 'b'])  # 'a' first, 'b' second

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

# `練習 Q02 (3,4,5)`

---

# Mod 09 Data Cleaning and Preparation
> ## missing values
><img src="./img/data_missing.jpg" style='width:100%'>

In [115]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 9-1 Handling Missing Data
><img src="./img/dropna01.png" style='width:80%'>
><img src="./img/drop01.png" style='width:80%'>

### np.nan / hasnans, isnull

In [117]:
data = pd.Series(['banana', 'orange', np.nan, 'avocado'])
print(f'data =\n{data}\n\n'
      f'hasnans = {data.hasnans}\n\n'
      f'notnull = \n{data.notnull()}\n\n' 
      f'isnull =\n{data.isnull()}')

data =
0     banana
1     orange
2        NaN
3    avocado
dtype: object

hasnans = True

notnull =
0     True
1     True
2    False
3     True
dtype: bool

isnull =
0    False
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data
#### import nan

In [119]:
from numpy import nan
data = pd.Series([1, nan, 3.5, nan, 7])
data, data.dropna() #過濾空值

(0    1.0
 1    NaN
 2    3.5
 3    NaN
 4    7.0
 dtype: float64,
 0    1.0
 2    3.5
 4    7.0
 dtype: float64)

In [120]:
data, data[data.notnull()]

(0    1.0
 1    NaN
 2    3.5
 3    NaN
 4    7.0
 dtype: float64,
 0    1.0
 2    3.5
 4    7.0
 dtype: float64)

In [121]:
data = pd.DataFrame([[1., 6.5, 3.], [1., nan, nan],
                     [nan, nan, nan], [nan, 6.5, 3.]])
cleaned = data.dropna()
print(f'{data}\n\n'
      f'{cleaned}')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0

In [122]:
data, data.dropna(how='all')

(     0    1    2
 0  1.0  6.5  3.0
 1  1.0  NaN  NaN
 2  NaN  NaN  NaN
 3  NaN  6.5  3.0,
      0    1    2
 0  1.0  6.5  3.0
 1  1.0  NaN  NaN
 3  NaN  6.5  3.0)

In [123]:
data[4] = nan    # column 4
data, data.dropna(axis=1, how='all')  # axis = 1 column

(     0    1    2   4
 0  1.0  6.5  3.0 NaN
 1  1.0  NaN  NaN NaN
 2  NaN  NaN  NaN NaN
 3  NaN  6.5  3.0 NaN,
      0    1    2
 0  1.0  6.5  3.0
 1  1.0  NaN  NaN
 2  NaN  NaN  NaN
 3  NaN  6.5  3.0)

In [124]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = nan
df.iloc[:2, 2] = nan
df.iloc[4, :] = nan
print(f'{df}\n\n'
      f'{df.dropna()}\n\n'
      f'{df.dropna(thresh=2)}')      # drop >=2 NaN and above

          0         1         2
0  0.114385       NaN       NaN
1 -0.197399       NaN       NaN
2 -0.006958       NaN  1.061541
3  0.390400       NaN  0.284046
4       NaN       NaN       NaN
5  0.173531  0.930671  1.086285
6 -1.158963  0.287378  0.585804

          0         1         2
5  0.173531  0.930671  1.086285
6 -1.158963  0.287378  0.585804

          0         1         2
2 -0.006958       NaN  1.061541
3  0.390400       NaN  0.284046
5  0.173531  0.930671  1.086285
6 -1.158963  0.287378  0.585804

### Filling In Missing Data
><img src="./img/fill01.png" style='width:100%'>

In [127]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = nan
df.iloc[:2, 2] = nan
df, df.fillna(0) #空值用0填滿

(          0         1         2
 0  0.098530       NaN       NaN
 1 -0.163264       NaN       NaN
 2  0.035176       NaN -0.240545
 3  0.141345       NaN -0.162040
 4 -0.663319  0.797468  0.204118
 5  0.134390  0.551600 -0.198400
 6  2.132347 -1.432261 -0.318606,
           0         1         2
 0  0.098530  0.000000  0.000000
 1 -0.163264  0.000000  0.000000
 2  0.035176  0.000000 -0.240545
 3  0.141345  0.000000 -0.162040
 4 -0.663319  0.797468  0.204118
 5  0.134390  0.551600 -0.198400
 6  2.132347 -1.432261 -0.318606)

In [130]:
df, df.fillna({1: 0.5, 2: 0})  # 1:, 2: columns

(          0         1         2
 0  0.098530       NaN       NaN
 1 -0.163264       NaN       NaN
 2  0.035176       NaN -0.240545
 3  0.141345       NaN -0.162040
 4 -0.663319  0.797468  0.204118
 5  0.134390  0.551600 -0.198400
 6  2.132347 -1.432261 -0.318606,
           0         1         2
 0  0.098530  0.500000  0.000000
 1 -0.163264  0.500000  0.000000
 2  0.035176  0.500000 -0.240545
 3  0.141345  0.500000 -0.162040
 4 -0.663319  0.797468  0.204118
 5  0.134390  0.551600 -0.198400
 6  2.132347 -1.432261 -0.318606)

### inplace

In [131]:
df1 = df.fillna(0, inplace=True)
df, df1  # inplace fill in df

(          0         1         2
 0  0.098530  0.000000  0.000000
 1 -0.163264  0.000000  0.000000
 2  0.035176  0.000000 -0.240545
 3  0.141345  0.000000 -0.162040
 4 -0.663319  0.797468  0.204118
 5  0.134390  0.551600 -0.198400
 6  2.132347 -1.432261 -0.318606,
 None)

### ffill

In [132]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = nan
df.iloc[4:, 2] = nan
print(df)
# df.fillna(method='ffill'), df.fillna(method='ffill', limit=1)
df.ffill(), df.ffill(limit=1)

          0         1         2
0 -0.931643 -0.328228  2.021343
1 -1.702771 -1.960942  0.841115
2 -1.882974       NaN -0.301035
3 -1.436833       NaN -0.608796
4 -1.528770       NaN       NaN
5  0.641634       NaN       NaN

(          0         1         2
 0 -0.931643 -0.328228  2.021343
 1 -1.702771 -1.960942  0.841115
 2 -1.882974 -1.960942 -0.301035
 3 -1.436833 -1.960942 -0.608796
 4 -1.528770 -1.960942 -0.608796
 5  0.641634 -1.960942 -0.608796,
           0         1         2
 0 -0.931643 -0.328228  2.021343
 1 -1.702771 -1.960942  0.841115
 2 -1.882974 -1.960942 -0.301035
 3 -1.436833       NaN -0.608796
 4 -1.528770       NaN -0.608796
 5  0.641634       NaN       NaN)

### fill mean. median

In [133]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

data, pd.concat([data, data.fillna(data.mean()), data.fillna(data.median())], axis=1)

(0    1.0
 1    NaN
 2    3.5
 3    NaN
 4    7.0
 dtype: float64,
      0         1    2
 0  1.0  1.000000  1.0
 1  NaN  3.833333  3.5
 2  3.5  3.500000  3.5
 3  NaN  3.833333  3.5
 4  7.0  7.000000  7.0)

### fill interpolation 有時間序

In [137]:
import pandas as pd
import numpy as np
s = pd.Series([0, 1, np.nan, np.nan, np.nan, 3, np.nan, np.nan, np.nan, 10])

pd.concat([s, s.interpolate(), s.interpolate(method='polynomial', order=2)], axis=1) 
# 線性補資料 order=2 -> 2次方

      0      1          2
0   0.0   0.00   0.000000
1   1.0   1.00   1.000000
2   NaN   1.50   1.648148
3   NaN   2.00   1.944444
4   NaN   2.50   2.268519
5   3.0   3.00   3.000000
6   NaN   4.75   4.138889
7   NaN   6.50   5.685185
8   NaN   8.25   7.638889
9  10.0  10.00  10.000000

## 09-2 Data Transformation

### Removing Duplicates
><img src="./img/duplicate01.png" style='width:100%'>

In [138]:
import pandas as pd
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [139]:
data.duplicated().any()

np.True_

### 完全重複

In [140]:
data.duplicated(), data.duplicated().sum()  # 完全重複

(0    False
 1    False
 2    False
 3    False
 4    False
 5    False
 6     True
 dtype: bool,
 np.int64(1))

In [141]:
data, data.drop_duplicates()

(    k1  k2
 0  one   1
 1  two   1
 2  one   2
 3  two   3
 4  one   3
 5  two   4
 6  two   4,
     k1  k2
 0  one   1
 1  two   1
 2  one   2
 3  two   3
 4  one   3
 5  two   4)

### keep = 'first'

In [142]:
data['v1'] = range(7)
data, data.drop_duplicates(['k1'])

(    k1  k2  v1
 0  one   1   0
 1  two   1   1
 2  one   2   2
 3  two   3   3
 4  one   3   4
 5  two   4   5
 6  two   4   6,
     k1  k2  v1
 0  one   1   0
 1  two   1   1)

### keep='last', False

In [144]:
data, data.drop_duplicates(['k1', 'k2'], keep='last')  
# k1,k2都一樣才算一樣 留最後下一筆, try False kill all

(    k1  k2  v1
 0  one   1   0
 1  two   1   1
 2  one   2   2
 3  two   3   3
 4  one   3   4
 5  two   4   5
 6  two   4   6,
     k1  k2  v1
 0  one   1   0
 1  two   1   1
 2  one   2   2
 3  two   3   3
 4  one   3   4
 6  two   4   6)

## 9-3 Replacing Values

In [145]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [146]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [147]:
data, data.replace([-999, -1000], np.nan)

(0       1.0
 1    -999.0
 2       2.0
 3    -999.0
 4   -1000.0
 5       3.0
 dtype: float64,
 0    1.0
 1    NaN
 2    2.0
 3    NaN
 4    NaN
 5    3.0
 dtype: float64)

In [149]:
# both are same
data, data.replace([-999, -1000], [np.nan, 0]), data.replace({-999: np.nan, -1000: 0})

(0       1.0
 1    -999.0
 2       2.0
 3    -999.0
 4   -1000.0
 5       3.0
 dtype: float64,
 0    1.0
 1    NaN
 2    2.0
 3    NaN
 4    0.0
 5    3.0
 dtype: float64,
 0    1.0
 1    NaN
 2    2.0
 3    NaN
 4    0.0
 5    3.0
 dtype: float64)

## 9-4 Discretization and Binning
### cut 以`值 value` 來切
><img src="./img/cut01.png" style='width:100%'>

In [150]:
ages = [12, 18, 20, 28, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[NaN, NaN, (18.0, 25.0], (25.0, 35.0], (18.0, 25.0], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 14
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [153]:
print(cats.codes, '\n') #-1表示空值 0表示落在第一個區間 1第二 以此類推
print(cats.categories, '\n') #所有類別
print(cats.value_counts()) #數量統計

[-1 -1  0  1  0  1  0  0  2  1  3  2  2  1]

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

(18, 25]     4
(25, 35]     4
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [152]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
print(f'ages\t : {ages}\n\n'
      f'bins\t : {bins}\n\n'
      f'pd.cut\t :\n{pd.cut(ages, bins, labels=group_names)}')

ages	 : [12, 18, 20, 28, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins	 : [18, 25, 35, 60, 100]

pd.cut	 :
[NaN, NaN, 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 14
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

### q_cut 等份 `比例`來切

In [159]:
data = np.random.randn(1000)  # Normal distributed
cats = pd.qcut(data, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])  # Cut into quartiles 四分位數
print(f'data[:20] :\n{data[:20]}\n\n'
      f'cats :\n{cats}\n\n'
      f'cats.codes[:50] :\n{cats.codes[:50]}\n\n'
      # f'pd.value_counts(cats) :\n{pd.value_counts(cats)}')
      f'pd.value_counts(cats) :\n{cats.value_counts()}')

data[:20] :
[-0.53061604 -1.02340656 -0.12720519  0.47399538  0.24059244  1.60762736
 -0.92874188 -1.07229458 -0.32482964 -0.3799786  -0.0812731   2.62873196
 -0.28152092 -0.80294429 -0.52100624 -0.96714158  0.15170875  0.94408702
 -0.99942058  0.41232211]

cats :
['Q2', 'Q1', 'Q2', 'Q3', 'Q3', ..., 'Q2', 'Q3', 'Q1', 'Q1', 'Q1']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

cats.codes[:50] :
[1 0 1 2 2 3 0 0 1 1 1 3 1 0 1 0 2 3 0 2 1 0 1 3 1 1 0 0 3 3 2 2 3 2 2 3 3
 2 0 0 1 3 0 1 3 2 3 1 0 2]

pd.value_counts(cats) :
Q1    250
Q2    250
Q3    250
Q4    250
Name: count, dtype: int64

### unequal inteval / 不等份 `比例`來切

In [160]:
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.], precision=5) #precision小數保留5位
print(f'{data[:20]}\n\n'
      f'{cats}\n\n'
      # f'{pd.value_counts(cats)}')
      f'{cats.value_counts()}')

[-0.53061604 -1.02340656 -0.12720519  0.47399538  0.24059244  1.60762736
 -0.92874188 -1.07229458 -0.32482964 -0.3799786  -0.0812731   2.62873196
 -0.28152092 -0.80294429 -0.52100624 -0.96714158  0.15170875  0.94408702
 -0.99942058  0.41232211]

[(-1.316, -0.025665], (-1.316, -0.025665], (-1.316, -0.025665], (-0.025665, 1.18817], (-0.025665, 1.18817], ..., (-1.316, -0.025665], (-0.025665, 1.18817], (-3.12962, -1.316], (-3.12962, -1.316], (-3.12962, -1.316]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.12962, -1.316] < (-1.316, -0.025665] < (-0.025665, 1.18817] < (1.18817, 2.92398]]

(-3.12962, -1.316]      100
(-1.316, -0.025665]     400
(-0.025665, 1.18817]    400
(1.18817, 2.92398]      100
Name: count, dtype: int64

---

# Mod 10 資料彙總和分組 Data Aggregation & Group Operations

函數    | 描述
------:|-------------
mean() | 計算各組的平均值
sum()   | 計算各組值的總和
size()  | 計算各組的大小
count() | 計算各組的數量
std()   | 計算各組的標準差
var()   | 計算各組的方差
sem()   | 計算各組平均值的標準誤差
describe() | 產生描述性統計信息
first() | 計算各組值的第一個值
last()  | 計算各組值的最後一個值
nth()   | 取第 n 個值，如果 n 是列表，則取其子集
min()   | 計算各組值的最小值
max()   | 計算各組值的最大值

In [161]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 11-1 df aggregation
> 對於 DataFrame，`預設`情況下，聚合函數傳回每個 `axis=0` 欄位的結果。

In [163]:
rng = np.random.RandomState(42)
df = pd.DataFrame({'A': rng.rand(5), 'B': rng.rand(5)})

print(f'df =\n{df}\n\n'
      f'df.count() =\n{df.count()}\n\n'
      f'df.mean() =\n{df.mean()}\n\n'
      f'df.median() =\n{df.median()}\n\n'
      f'df.min() =\n{df.min()}\n\n'
      f'df.max() =\n{df.max()}\n\n'
      f'df.std() =\n{df.std()}\n\n'
      f'df.quantile(.5) =\n{df.quantile(.5)}')

df =
          A         B
0  0.374540  0.155995
1  0.950714  0.058084
2  0.731994  0.866176
3  0.598658  0.601115
4  0.156019  0.708073

df.count() =
A    5
B    5
dtype: int64

df.mean() =
A    0.562385
B    0.477888
dtype: float64

df.median() =
A    0.598658
B    0.601115
dtype: float64

df.min() =
A    0.156019
B    0.058084
dtype: float64

df.max() =
A    0.950714
B    0.866176
dtype: float64

df.std() =
A    0.308748
B    0.353125
dtype: float64

df.quantile(.5) =
A    0.598658
B    0.601115
Name: 0.5, dtype: float64

### agg function vs. describe (聚合)
> agg 返回的也是一個DataFrame。很多功能用 sum、mean 等等也可以實現。但是 agg 更加簡潔, 而且傳給它的函數可以是字串，也可以自訂，參數是column對應的子DataFrame。

In [164]:
print(f"df.agg('mean') :\n{df.agg('mean')}\n{'-'*60}\n"
      f"df.agg(['count', 'mean', 'std', 'min', 'max'] :\n{df.agg(['count', 'mean', 'std', 'min', 'max'])}\n{'-'*60}\n"
      f'df.describe() :\n{df.describe()}')

df.agg('mean') :
A    0.562385
B    0.477888
dtype: float64
------------------------------------------------------------
df.agg(['count', 'mean', 'std', 'min', 'max'] :
              A         B
count  5.000000  5.000000
mean   0.562385  0.477888
std    0.308748  0.353125
min    0.156019  0.058084
max    0.950714  0.866176
------------------------------------------------------------
df.describe() :
              A         B
count  5.000000  5.000000
mean   0.562385  0.477888
std    0.308748  0.353125
min    0.156019  0.058084
25%    0.374540  0.155995
50%    0.598658  0.601115
75%    0.731994  0.708073
max    0.950714  0.866176

In [167]:
print(f'df :\n{df}\n{"-"*60}\n'
      f"df.mean(axis='columns') :\n{df.mean(axis='columns')}\n{'-'*60}\n"
      f'df.mean(axis=1) :\n{df.mean(axis=1)}')

df :
          A         B
0  0.374540  0.155995
1  0.950714  0.058084
2  0.731994  0.866176
3  0.598658  0.601115
4  0.156019  0.708073
------------------------------------------------------------
df.mean(axis='columns') :
0    0.265267
1    0.504399
2    0.799085
3    0.599887
4    0.432046
dtype: float64
------------------------------------------------------------
df.mean(axis=1) :
0    0.265267
1    0.504399
2    0.799085
3    0.599887
4    0.432046
dtype: float64

## 10-2 Series 彙總  & 排序

In [165]:
ser1 = pd.Series([1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 20, 30, 40, 50, 60])
print (f'ser1.sum()\t= {ser1.sum()}\n'
       f'ser1.min()\t= {ser1.min()}\n'
       f'ser1.max()\t= {ser1.max()}\n'
       f'ser1.mean()\t= {ser1.mean()}\n'
       f'ser1.count()\t= {ser1.count()}\n'
       f'ser1.median()\t= {ser1.median()}\n'
       f'ser1.mode()\t= {ser1.mode()[0]}\n'
       f'ser1.std()\t= {ser1.std()}')

ser1.sum()	= 251
ser1.min()	= 1
ser1.max()	= 60
ser1.mean()	= 16.733333333333334
ser1.count()	= 15
ser1.median()	= 7.0
ser1.mode()	= 6
ser1.std()	= 19.12540071164399

In [166]:
print (f'ser1.describe() =\n{ser1.describe()}\n\n'
       f'ser1.max()- ser1.min() = {ser1.max()- ser1.min()}\n\n'     # 最高和最低差多少 (統計 全距)
       f'ser1.agg(["mean", "sum", "min", max"]) =\n{ser1.agg(["mean", "sum", "min", "max"])}\n') # agg = aggregate

ser1.describe() =
count    15.000000
mean     16.733333
std      19.125401
min       1.000000
25%       4.500000
50%       7.000000
75%      25.000000
max      60.000000
dtype: float64

ser1.max()- ser1.min() = 59

ser1.agg(["mean", "sum", "min", max"]) =
mean     16.733333
sum     251.000000
min       1.000000
max      60.000000
dtype: float64

### df.columns (a Sereis)

In [168]:
import numpy as np
import pandas as pd
rng = np.random.RandomState(42)
df = pd.DataFrame({'A': rng.rand(5), 'B': rng.rand(5)})

print(f'df =\n{df}\n\n'
      f'A.mean \t\t= {df.A.mean()}\n'
      f'B.median()\t= {df["B"].median()}\n'  #df.B = df["B"]
      f'A.min\t\t= {df.A.min()}\n'
      f'B.max\t\t= {df.B.max()}\n'
      f'A.std\t\t= {df.A.std()}')

df =
          A         B
0  0.374540  0.155995
1  0.950714  0.058084
2  0.731994  0.866176
3  0.598658  0.601115
4  0.156019  0.708073

A.mean 		= 0.5623850983416314
B.median()	= 0.6011150117432088
A.min		= 0.15601864044243652
B.max		= 0.8661761457749352
A.std		= 0.30874824961862174

## 10-3 GroupBy Mechanics
> 用 groupby 進行資料分組，可以看做是基於行（或者說是index）操作的話，則 agg 函數則是基於`列`的聚合操作。

> groupby 返回的是一個 DataFrameGroupBy 結構，這個結構必須調用彙總函式（如sum）之後，才會得到結構為 Series 的資料結果。用 groupby 函數後，要接類似 sum、mean 等彙總函式才能輸出

><img src="./img/groupby.jpg"  style='width:100%'>

In [169]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.312826  1.059023
1    a  two  0.743203 -1.999144
2    b  one  0.486722 -1.468601
3    b  two  0.707372  0.464986
4    a  one -1.649890 -0.529167

In [170]:
grouped = df['data1'].groupby(df['key1'])
grouped  # object 物件

In [171]:
grouped.mean(), grouped.sum()

(key1
 a   -0.197954
 b    0.597047
 Name: data1, dtype: float64,
 key1
 a   -0.593861
 b    1.194093
 Name: data1, dtype: float64)

In [172]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()
df, means

(  key1 key2     data1     data2
 0    a  one  0.312826  1.059023
 1    a  two  0.743203 -1.999144
 2    b  one  0.486722 -1.468601
 3    b  two  0.707372  0.464986
 4    a  one -1.649890 -0.529167,
 key1  key2
 a     one    -0.668532
       two     0.743203
 b     one     0.486722
       two     0.707372
 Name: data1, dtype: float64)

<center><h1>--- The End ---</h1></center>