# Mod 11 時間序列 Time Series
> pandas 最基本的時間序列型別就是以時間戳（TimeStamp）為 `index` 元素的 Series 型別。

> pandas提供了一組標準的時間序列，輕鬆地`進行切片/切塊、聚合、對定期/不定期的時間序列進行重取樣`等。這些工具中大部分都對金融和經濟資料尤其有用。

> pandas中有四種時間型別：

> * Date times : 日期和時間，可以帶時區。和標準庫中的 datetime.datetime 類似。
> * Time deltas： 絕對持續時間，和 標準庫中的 datetime.timedelta 類似。
> * Time spans： 由時間點及其關聯的頻率定義的時間跨度。
> * Date offsets：基於日曆計算的時間 和 dateutil.relativedelta.relativedelta 類似。

> ### 摘要 ：

類型         | 說明            | 類似 Python 類別     | pandas 物件    
------------ | -------------- | -------------------- | --------------
Date times   | 單一時間點      | `datetime.datetime`  | `Timestamp`   
Time deltas  | 時間差          | `datetime.timedelta` | `Timedelta`   
Time spans   | 具有頻率的時間段 | 無直接對應           | `Period`    
Date offsets | 日曆偏移量      | `relativedelta`      | `DateOffset`, `MonthEnd`, `YearBegin`, 等

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 11-1 Date and Time Data Types and Tools

### Pandas NOW

In [3]:
pd.to_datetime("today"), pd.Timestamp('now'), pd.Timestamp.now()   #抓電腦時間

(Timestamp('2026-07-16 09:04:43.675285'),
 Timestamp('2026-07-16 09:04:43.677974'),
 Timestamp('2026-07-16 09:04:43.677987'))

### pd.to_datetime / Index

In [5]:
datestrs = ['2021-07-06 12:00:00', '2018-08-06 00:00:00']
pd.to_datetime(datestrs) #文字轉換成時間格式

DatetimeIndex(['2021-07-06 12:00:00', '2018-08-06 00:00:00'], dtype='datetime64[ns]', freq=None)

### Timestamp 時間戳 : 時間戳表示某個具體的時間點

In [7]:
pd.Timestamp(2012, 5, 1), pd.Timestamp('2012-05-01'), pd.to_datetime('2012-05-01') 
#數字文字都可轉成時間格式，用文字方式轉檔時較不會有問題

(Timestamp('2012-05-01 00:00:00'),
 Timestamp('2012-05-01 00:00:00'),
 Timestamp('2012-05-01 00:00:00'))

## Timedelta 是 Pandas 庫中用來表示時間間隔（Duration）或時間差的物件

In [8]:
import pandas as pd

# 1. 建立一個時間點 (Timestamp)
start_time = pd.Timestamp("2026-06-13 10:00:00")
print(f"開始時間\t\t: {start_time}")

# 2. 建立一個時間間隔 (Timedelta) -> 2天又5個小時
time_delay = pd.Timedelta(days=2, hours=5)
# 也可以用字串建立：pd.Timedelta('2 days 5 hours')
print(f"時間間隔\t\t: {time_delay}")

開始時間		: 2026-06-13 10:00:00
時間間隔		: 2 days 05:00:00

In [10]:
# 3. 進行時間運算（時間點 + 時間間隔）
end_time = start_time + time_delay
print(f"結束時間\t\t: {end_time}\n"
      f"結束時間 date\t: {end_time.date()}, time : {end_time.time()}\n") #各自抓日期 、時間

# 4. 計算兩個時間點的差值（會自動自動生成 Timedelta）
time_diff = end_time - start_time
print(f"兩者差距\t\t: {time_diff}\n"
      f"型態為\t\t: {type(time_diff)})")

結束時間		: 2026-06-15 15:00:00
結束時間 date	: 2026-06-15, time : 15:00:00

兩者差距		: 2 days 05:00:00
型態為		: <class 'pandas._libs.tslibs.timedeltas.Timedelta'>)

## 11-2 Time Series Basics

In [12]:
from datetime import datetime
dates = [datetime(2021, 1, 2), datetime(2021, 1, 5), datetime(2021, 1, 7),
         datetime(2021, 1, 8), datetime(2021, 1, 10), datetime(2021, 1, 12)]
ts = pd.Series(np.random.randn(6), index=dates)   # date index
print(f'{ts}\n\n'
      f'{ts.index}\n\n'
      f'{ts[::2]}\n\n'
      f'{ts+ts[::2]}') #日期不合 無法相加

2021-01-02   -0.485610
2021-01-05   -0.665229
2021-01-07    0.857794
2021-01-08   -0.618204
2021-01-10   -2.401155
2021-01-12   -1.057152
dtype: float64

DatetimeIndex(['2021-01-02', '2021-01-05', '2021-01-07', '2021-01-08',
               '2021-01-10', '2021-01-12'],
              dtype='datetime64[ns]', freq=None)

2021-01-02   -0.485610
2021-01-07    0.857794
2021-01-10   -2.401155
dtype: float64

2021-01-02   -0.971220
2021-01-05         NaN
2021-01-07    1.715588
2021-01-08         NaN
2021-01-10   -4.802310
2021-01-12         NaN
dtype: float64

### Indexing, Selection, Subsetting
#### pd.date_range

In [ ]:
pd.date_range('1-1-2018', periods=1000, freq='D')  # periods default freq='D'

In [13]:
data = np.random.randint(1000, 5000, (1000))  # 1000 to 4999 pick 1000
series1 = pd.Series(data,  index = pd.date_range('1-1-2019', periods=1000, freq='B'))  # periods
# B是工作日
print (f'series1 :\n{series1}\n\n')

series1.sort_values(ascending=True, inplace = True)  # note : inplace
# series1.sort_values(ascending=False, inplace = True)
# series1.sort_index(ascending=False, inplace = True)
print(f'series1.sort_values :\n{series1}\n\n'
      f'series1.index[:6] :\n{series1.index[:6]}\n\n'      # series1 已被排序
      f'series1.index.year[:6] :\n{series1.index.year[:6]}\n\n'
      f'series1.index.month[:6] :\n{series1.index.month[:6]}')

series1 :
2019-01-01    4822
2019-01-02    1573
2019-01-03    4510
2019-01-04    1782
2019-01-07    1122
              ...
2022-10-25    1426
2022-10-26    4368
2022-10-27    4223
2022-10-28    1043
2022-10-31    2999
Freq: B, Length: 1000, dtype: int32


series1.sort_values :
2022-06-27    1002
2021-10-05    1004
2020-03-17    1008
2022-08-11    1008
2019-01-18    1018
              ...
2019-07-10    4981
2022-08-05    4982
2019-01-10    4991
2020-03-10    4996
2019-01-24    4997
Length: 1000, dtype: int32

series1.index[:6] :
DatetimeIndex(['2022-06-27', '2021-10-05', '2020-03-17', '2022-08-11',
               '2019-01-18', '2019-09-11'],
              dtype='datetime64[ns]', freq=None)

series1.index.year[:6] :
Index([2022, 2021, 2020, 2022, 2019, 2019], dtype='int32')

series1.index.month[:6] :
Index([6, 10, 3, 8, 1, 9], dtype='int32')

### 所有紀錄中, 最高紀錄前 5 筆 ? 最低紀錄 5 筆 ?

In [14]:
print(f'series1.sort_values :\n{series1.sort_values(ascending=False).iloc[0:5]}\n')

series1.sort_values(ascending=False, inplace= True)
print(f'series1.iloc[0:5] :\n{series1.iloc[0:5]}\n\n'
      f'series1.head() :\n{series1.head()}\n\n'
      f'series1.tail(5) :\n{series1.tail(5)}')

series1.sort_values :
2019-01-24    4997
2020-03-10    4996
2019-01-10    4991
2022-08-05    4982
2019-07-10    4981
dtype: int32

series1.iloc[0:5] :
2019-01-24    4997
2020-03-10    4996
2019-01-10    4991
2022-08-05    4982
2019-07-10    4981
dtype: int32

series1.head() :
2019-01-24    4997
2020-03-10    4996
2019-01-10    4991
2022-08-05    4982
2019-07-10    4981
dtype: int32

series1.tail(5) :
2019-01-18    1018
2020-03-17    1008
2022-08-11    1008
2021-10-05    1004
2022-06-27    1002
dtype: int32

### slice by year, month or trancate

In [16]:
ts = pd.Series(np.random.randint(10, 100, 1000), index=pd.date_range('1/1/2018', periods=1000))
print(f'ts :\n{ts}\n\n'
      f"ts['2018'] :\n{ts['2018']}\n\n"
      f"ts['2018-05'][:] :\n{ts['2018-05'][:]}\n\n" #5月整月
      f"ts.truncate(after='1/9/2018') :\n{ts.truncate(after='1/9/2018')}\n\n" #1/9(不含)以後刪除
      f"ts.truncate(before='1/9/2018') :\n{ts.truncate(before='1/9/2018')}")

ts :
2018-01-01    83
2018-01-02    77
2018-01-03    57
2018-01-04    56
2018-01-05    92
              ..
2020-09-22    14
2020-09-23    68
2020-09-24    44
2020-09-25    22
2020-09-26    56
Freq: D, Length: 1000, dtype: int32

ts['2018'] :
2018-01-01    83
2018-01-02    77
2018-01-03    57
2018-01-04    56
2018-01-05    92
              ..
2018-12-27    94
2018-12-28    97
2018-12-29    92
2018-12-30    53
2018-12-31    44
Freq: D, Length: 365, dtype: int32

ts['2018-05'][:] :
2018-05-01    80
2018-05-02    73
2018-05-03    71
2018-05-04    53
2018-05-05    74
2018-05-06    16
2018-05-07    92
2018-05-08    12
2018-05-09    87
2018-05-10    97
2018-05-11    33
2018-05-12    77
2018-05-13    93
2018-05-14    36
2018-05-15    37
2018-05-16    58
2018-05-17    14
2018-05-18    43
2018-05-19    23
2018-05-20    11
2018-05-21    87
2018-05-22    18
2018-05-23    38
2018-05-24    61
2018-05-25    51
2018-05-26    78
2018-05-27    18
2018-05-28    11
2018-05-29    19
2018-05-30    52
2018-05-31    39
Freq: D, dtype: int32

ts.truncate(after='1/9/2018') :
2018-01-01    83
2018-01-02    77
2018-01-03    57
2018-01-04    56
2018-01-05    92
2018-01-06    97
2018-01-07    55
2018-01-08    65
2018-01-09    27
Freq: D, dtype: int32

ts.truncate(before='1/9/2018') :
2018-01-09    27
2018-01-10    50
2018-01-11    69
2018-01-12    83
2018-01-13    16
              ..
2020-09-22    14
2020-09-23    68
2020-09-24    44
2020-09-25    22
2020-09-26    56
Freq: D, Length: 992, dtype: int32

### resample 
### 常用頻率與日期偏移量

頻率                 |            日期偏移量 | 說明
--------------------:|---------------------|-----
D                     | Day                 | 日曆日
B	                  | BusinessDay         | 工作日
H                     | Hour	            | 小時
T 或 min              | Minute	            | 分
S                     | Second	            | 秒
L 或 ms	              | Milli	            | 毫秒
U	                  | Micro	            | 微秒
ME	                  | MonthEnd	        | 每月最後一個日曆日
BME	                  | BusinessMonthEnd    | 每月最後一個工作日
MS	                  | MonthBegin          | 每月第一個日曆日
BMS	                  | BussinessMonthBegin | 每月第一個工作日
W-MON、W-TUE、…	      | Week                | 指定星期幾 (MON、TUE、WED、THU、FRI、SAT、SUN)
WOM-1MON、WOM-2MON、… | WeekOfMonth	        | 產生每月第一、第二、第三或第四周的星期幾。例如WOM-3FRI表示每月第3個星期五
Q-JAN、Q-FEB、…	      | QuarterEnd	         | 以指定月份結束的年度，每季度最後一個月的最後一個日曆日
BQ-JAN、BQ-FEB、…	  | BusinessQuarterEnd	 | 以指定月份結束的年度，每季度最後一個月的最後一個工作日
QS-JAN、QS-FEB、…	  | QuarterBegin	     | 以指定月份結束的年度，每季度最後一個月的第一個日曆日
BQS-JAN、BQS-FEB、…	  | BusinessQuarterBegin | 以指定月份結束的年度，每季度最後一個月的第一個工作日
A-JAN、A-FEB、…	      | YearEnd              | 每年指定月份的最後一個日曆日
BA-JAN、BA-FEB、…	  | BusinessYearEnd	     | 每年指定月份的最後一個工作日
AS-JAN、AS-FEB、…	  | YearBegin	         | 每年指定月份的第一個日曆日
BAS-JAN、BAS-FEB、…	  | BusinessYearBegin	 | 每年指定月份的第一個工作日

In [17]:
resampler = ts.resample(rule='BME').sum()  # try sum 2D : 2 days, M
print(f'{ts[:10]}\n\n'
      f'{resampler[:10]}\n')

2018-01-01    83
2018-01-02    77
2018-01-03    57
2018-01-04    56
2018-01-05    92
2018-01-06    97
2018-01-07    55
2018-01-08    65
2018-01-09    27
2018-01-10    50
Freq: D, dtype: int32

2018-01-31    1721
2018-02-28    1431
2018-03-30    1795
2018-04-30    1732
2018-05-31    1552
2018-06-29    1720
2018-07-31    1440
2018-08-31    1581
2018-09-28    1452
2018-10-31    1828
Freq: BME, dtype: int32

### freq 設置一定的時間間隔
http://liao.cpython.org/pandas34.html

In [18]:
dates = pd.date_range('1-1-2020', periods=100, freq='W-WED') #每周星期三
# dates = pd.date_range('1/1/2000', periods=100, freq='Y')
long_df = pd.DataFrame(np.random.randn(100, 4), index=dates,
                       columns=['Colorado', 'Texas', 'New York', 'Ohio'])
print(f'long_df :\n{long_df}\n\n\n'
      f"long_df.loc['12/2020'] :\n{long_df.loc['12/2020']}")

long_df :
            Colorado     Texas  New York      Ohio
2020-01-01  1.206702 -0.386863 -0.945098 -0.221155
2020-01-08  0.567312 -0.495362 -1.131287  0.524552
2020-01-15 -1.018120  0.859331 -0.169424  0.745511
2020-01-22  1.080317  0.268777 -0.015523  1.257823
2020-01-29 -1.728883 -0.353932 -0.879614  1.139004
...              ...       ...       ...       ...
2021-10-27 -2.196920 -1.846151 -1.648800  0.024522
2021-11-03 -1.161540  0.128506  1.878954  1.237548
2021-11-10 -0.421765 -0.507074 -1.891580  0.613353
2021-11-17  1.121486  1.375720  0.716680  0.647622
2021-11-24  0.398443 -0.531502  0.750133 -1.742553

[100 rows x 4 columns]


long_df.loc['12/2020'] :
            Colorado     Texas  New York      Ohio
2020-12-02  1.301746  0.865878 -0.157172 -0.067739
2020-12-09  0.968958 -2.902700  0.754091  0.041554
2020-12-16  0.032950 -0.977596 -0.169693  0.182301
2020-12-23 -1.134095 -1.261891  0.633172 -0.543719
2020-12-30  0.703933 -0.003186 -0.975278  0.844643

## 11-3 Date Ranges, Frequencies, and Shifting

### Generating Date Ranges

In [19]:
index = pd.date_range('2021-04-01', '2021-06-01', freq='W')  # try freq = 'W', 'S'
index

DatetimeIndex(['2021-04-04', '2021-04-11', '2021-04-18', '2021-04-25',
               '2021-05-02', '2021-05-09', '2021-05-16', '2021-05-23',
               '2021-05-30'],
              dtype='datetime64[ns]', freq='W-SUN')

### fix start or end point

In [20]:
pd.date_range(start='2021-04-01', periods=20), pd.date_range(end='2021-06-01', periods=20)

(DatetimeIndex(['2021-04-01', '2021-04-02', '2021-04-03', '2021-04-04',
                '2021-04-05', '2021-04-06', '2021-04-07', '2021-04-08',
                '2021-04-09', '2021-04-10', '2021-04-11', '2021-04-12',
                '2021-04-13', '2021-04-14', '2021-04-15', '2021-04-16',
                '2021-04-17', '2021-04-18', '2021-04-19', '2021-04-20'],
               dtype='datetime64[ns]', freq='D'),
 DatetimeIndex(['2021-05-13', '2021-05-14', '2021-05-15', '2021-05-16',
                '2021-05-17', '2021-05-18', '2021-05-19', '2021-05-20',
                '2021-05-21', '2021-05-22', '2021-05-23', '2021-05-24',
                '2021-05-25', '2021-05-26', '2021-05-27', '2021-05-28',
                '2021-05-29', '2021-05-30', '2021-05-31', '2021-06-01'],
               dtype='datetime64[ns]', freq='D'))

### BM : business month end frequency

In [21]:
pd.date_range('2000-01-01', '2000-12-01', freq='BME')  # BM : business month end frequency

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-28',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-29', '2000-10-31', '2000-11-30'],
              dtype='datetime64[ns]', freq='BME')

In [22]:
pd.date_range('2012-05-02 12:56:31', periods=5)  # base on days

DatetimeIndex(['2012-05-02 12:56:31', '2012-05-03 12:56:31',
               '2012-05-04 12:56:31', '2012-05-05 12:56:31',
               '2012-05-06 12:56:31'],
              dtype='datetime64[ns]', freq='D')

In [23]:
pd.date_range('2012-05-02 12:56:31', periods=5, normalize=True)  # date only

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

### Week of month dates

In [24]:
rng = pd.date_range('2012-01-01', '2012-09-01', freq='WOM-3FRI')  # 3th Fridays of each month
rng

DatetimeIndex(['2012-01-20', '2012-02-17', '2012-03-16', '2012-04-20',
               '2012-05-18', '2012-06-15', '2012-07-20', '2012-08-17'],
              dtype='datetime64[ns]', freq='WOM-3FRI')

# `練習 Q02 (6,7,8)`

---

# Mod 12 Data Loading, Storage
><img src="./img/data_loading.jpg"  style='width:100%'>

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 12-1 Reading and Writing Data in Text Format

## read csv

In [32]:
df = pd.read_csv('./data/ex1.csv')
df, type(df), df.index, df.columns, df.values

(   a   b   c   d message
 0  1   2   3   4   hello
 1  5   6   7   8   world
 2  9  10  11  12     foo,
 pandas.core.frame.DataFrame,
 RangeIndex(start=0, stop=3, step=1),
 Index(['a', 'b', 'c', 'd', 'message'], dtype='object'),
 array([[1, 2, 3, 4, 'hello'],
        [5, 6, 7, 8, 'world'],
        [9, 10, 11, 12, 'foo']], dtype=object))

In [27]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### observation

In [28]:
print(f'df :\n{df}\n\n'
      f'df.index\t: {df.index}\n'
      f'df.columns\t: {df.columns}\n\n'
      f'df.values :\n{df.values}\n\n'
      f'type(df.values) :\n{type(df.values)}\n'
      f'df.ndim : {df.ndim}\n'
      f'df.shape : {df.shape}\n\n'
      f'df.describe() :\n{df.describe()}\n\n'
      f'df.info :\n{df.info()}\n\n'
      f'df.head(4) :\n{df.head(4)}\n\n'          # default top 5 rows
      f'df.tail(4) :\n{df.tail(4)}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   a        3 non-null      int64
 1   b        3 non-null      int64
 2   c        3 non-null      int64
 3   d        3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes
df :
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

df.index	: RangeIndex(start=0, stop=3, step=1)
df.columns	: Index(['a', 'b', 'c', 'd', 'message'], dtype='object')

df.values :
[[1 2 3 4 'hello']
 [5 6 7 8 'world']
 [9 10 11 12 'foo']]

type(df.values) :
<class 'numpy.ndarray'>
df.ndim : 2
df.shape : (3, 5)

df.describe() :
         a     b     c     d
count  3.0   3.0   3.0   3.0
mean   5.0   6.0   7.0   8.0
std    4.0   4.0   4.0   4.0
min    1.0   2.0   3.0   4.0
25%    3.0   4.0   5.0   6.0
50%    5.0   6.0   7.0   8.0
75%    7.0   8.0   9.0  10.0
max    9.0  10.0  11.0  12.0

df.info :
None

df.head(4) :
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

df.tail(4) :
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### read table

In [29]:
pd.read_table('data/ex1.csv', sep=',')  # try sep=','
# pd.read_table('data/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### read  with name : ex2.csv no header/ column name

In [37]:
# pd.read_csv('data/ex2.csv')
#pd.read_csv('data/ex2.csv', header=None)  # try header = 0, 1 不要表頭的用法
pd.read_csv('data/ex2.csv', names=['aa', 'bb', 'cc', 'dd', 'message'])  # try to remove 'b' or ...

   aa  bb  cc  dd message
0   1   2   3   4   hello
1   5   6   7   8   world
2   9  10  11  12     foo

### read  with name / index_col

In [39]:
names = ['aa', 'bb', 'cc', 'dd', 'message']
pd.read_csv('data/ex2.csv', names=names, index_col='message')

         aa  bb  cc  dd
message
hello     1   2   3   4
world     5   6   7   8
foo       9  10  11  12

## read : txt

In [40]:
# open('data/ex3.txt')
list(open('./data/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [46]:
result = pd.read_table('data/ex3.txt', sep=r'\s+')   # re \s+ space 一個或多格連續空格
#result = pd.read_table('data/ex3.txt', sep=' ')   # re \s+ space
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

## 記憶體內的文字資料串流也可以使用 StringIO 物件建立, StringIO 是Python 的一個模組，它允許你`像操作檔案一樣操作字串`

In [47]:
from io import StringIO
data = """
Sample  Nationality  Handedness
1   USA  Right-handed
2   Japan    Left-handed
3   USA  Right-handed
4   Japan    Right-handed
5   Japan    Left-handed
6   Japan    Right-handed
7   USA  Right-handed
8   USA  Left-handed
9   Japan    Right-handed
10  USA  Right-handed"""
data = pd.read_table(StringIO(data), sep=r'\s+')
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

### read : skiprows

In [48]:
# pd.read_csv('data/ex4.csv')
pd.read_csv('data/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [49]:
result = pd.read_csv('data/ex5.csv')
print(f'{result}\n\n'
      f'{pd.isnull(result)}')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

### indicate na_values

In [51]:
result1 = pd .read_csv('data/ex5.csv')
result2 = pd.read_csv('data/ex5.csv', na_values='foo')  # assign 'foo' = NaN
result1, '\n', result2

(  something  a   b     c   d message
 0       one  1   2   3.0   4     NaN
 1       two  5   6   NaN   8   world
 2     three  9  10  11.0  12     foo,
 '\n',
   something  a   b     c   d message
 0       one  1   2   3.0   4     NaN
 1       two  5   6   NaN   8   world
 2     three  9  10  11.0  12     NaN)

In [50]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('data/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

### Reading Text Files in Pieces

In [52]:
result = pd.read_csv('data/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

### read : 5 rows

In [54]:
pd.read_csv('data/ex6.csv', nrows=5) #讀5行就好

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

### Writing Data to Text Format

In [55]:
data = pd.read_csv('data/ex5.csv')
data, type(data)

(  something  a   b     c   d message
 0       one  1   2   3.0   4     NaN
 1       two  5   6   NaN   8   world
 2     three  9  10  11.0  12     foo,
 pandas.core.frame.DataFrame)

In [56]:
data.to_csv('data/out.csv')  # write to file CSV

In [58]:
import sys
data.to_csv(sys.stdout, sep='|')  # sys.stdout -> Screen,,  like print
#標準輸出至螢幕

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

### 爬蟲寫入 CSV 檔

In [59]:
import pandas as pd

url = 'https://www.stockq.org/'
df = pd.read_html(url)

print(df[12].head())

df_data = df[12]

df_data.to_csv('./data/exchange_rate.csv', index=False, header=False)

                                                   0  \
0  亞洲股市指數行情 股市 指數 漲跌 比例 當地 紐西蘭 13654.22 19.15 0.1...

                                                   1  \
0  歐洲股市指數、非洲股市指數 股市 指數 漲跌 比例 當地 道瓊歐洲50 6270.75 -9...

                                                   2
0  美洲股市指數行情 股市 指數 漲跌 比例 當地 道瓊工業 52658.52 150.25 0...

## JSON Data
JSON 可能是`物件或字串`。當你想從 JSON中讀取資料時，JSON可作為物件；當要跨網路傳送 JSON 時，就會是字串。

json.loads 用於解碼 JSON 資料。該函數返回 Python 欄位的資料 dict 類型。

In [60]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""
type(obj)

str

In [61]:
import json
import pandas as pd
result = json.loads(obj)                                # to dictionary
df=pd.DataFrame.from_dict(result, orient="index")
# df=pd.DataFrame.from_dict(result)
print(f'obj : {type(obj)}\n'
      f'\nobj ={obj}\n\n'                                 # string
      f'result :\t{type(result)}\nresult :{result}\n\n\n' #  dict
      f'type(df) :\t{type(df)}\n\ndf.T :\n{df.T}')
df

obj : <class 'str'>

obj =
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}


result :	<class 'dict'>
result :{'name': 'Wes', 'places_lived': ['United States', 'Spain', 'Germany'], 'pet': None, 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']}, {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}


type(df) :	<class 'pandas.core.frame.DataFrame'>

df.T :
  name                     places_lived   pet  \
0  Wes  [United States, Spain, Germany]  None

                                            siblings
0  [{'name': 'Scott', 'age': 30, 'pets': ['Zeus',...

                                                              0
name                                                        Wes
places_lived                    [United States, Spain, Germany]
pet                                                        None
siblings      [{'name': 'Scott', 'age': 30, 'pets': ['Zeus',...

In [62]:
df.T

,name,places_lived,pet,siblings
0,Wes,"[United States, Spain, Germany]",None,"[{'name': 'Scott', 'age': 30, 'pets': ['Zeus',..."

#### json.dumps 用於將 Python 在後端就需要將`字典`轉換成通用的 Json 格式。

In [66]:
asjson = json.dumps(result) #轉成字串
print(f'{asjson},\n\n {type(asjson)}')

{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]},

 <class 'str'>

In [64]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age', 'pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [65]:
data = pd.read_json('data/example.json')
# df = pd.DataFrame.from_dict('data/example.json')
# df=pd.DataFrame.from_dict(result, orient="index")

data   # type(data)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

### Convert the object to a JSON string.

In [67]:
print(f'{data}\n\n'
      f'{data.to_json()}\n\n'
      f"{data.to_json(orient='records')}")

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### 爬蟲寫入 json 檔

In [68]:
import json
import requests

url = "https://www.googleapis.com/books/v1/volumes?maxResults=5&q=Python&projection=lite"
jsonfile = "./data/Books.json"
r = requests.get(url)
r.encoding = "utf8"
json_data = json.loads(r.text)
with open(jsonfile, 'w') as fp:
    json.dump(json_data, fp)

# print(r.text)
result = json.loads(r.text)                                # to dictionary
df=pd.DataFrame.from_dict(result, orient="index")
df.T

                                                     error
code                                                   429
message  Quota exceeded for quota metric 'Queries' and ...
errors   [{'message': 'Quota exceeded for quota metric ...
status                                  RESOURCE_EXHAUSTED
details  [{'@type': 'type.googleapis.com/google.rpc.Err...

## 12-2 Reading Microsoft Excel Files & SQLite
> #### pip install xlrd==1.2.0
> #### pip install openpyxl

In [70]:
frame = pd.read_excel('data/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
frame.to_excel('data/ex2.xlsx', sheet_name='Sheet1')

In [ ]:
frame.to_excel('data/ex2.xlsx')

### SQLite with Pandas
> #### 給你一個「工程師常用判斷公式」
>>是否會有「同時多人寫入」？
>> * 是 → MySQL / PostgreSQL<br>
>> * 否 → SQLite

面向               | SQLite           | MySQL / PostgreSQL
------------------:| ---------------- | ----------
架構               | 單一檔案          | Client–Server 
是否有 DB Server    | ❌ 沒有         | ✅ 有 
同時讀取            | 多人 OK          | 多人 OK
同時寫入            | ❌ 幾乎只能 1 個 | ✅ 多個
鎖定方式            | 整個資料庫鎖      | Row / MVCC
適合資料量          | 小～中            | 中～超大
網路存取            | 不適合            | 原生支援
備份 / Replication | 很弱              | 非常成熟
權限管理            | 幾乎沒有          | 非常完整

In [71]:
import pandas as pd
import sqlite3 as sql

df = pd.read_csv('./data/RegularSeasonCompactResults.csv')
df.head(), df.shape

(   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
 0    1985      20   1228      81   1328      64    N      0
 1    1985      25   1106      77   1354      70    H      0
 2    1985      25   1112      63   1223      56    H      0
 3    1985      25   1165      70   1432      54    H      0
 4    1985      25   1192      86   1447      74    H      0,
 (145289, 8))

In [72]:
# connect to db. if db is not exist, it will create a new one
conn = sql.connect("./data/db_example.db")

In [73]:
# insert dataframe into table. If table exist, it would replace it
# df.to_sql("example_table", conn, if_exists="replace", index=False)
df.to_sql("example_table", conn, if_exists="replace", index=False)

145289

In [74]:
# query from DB 
df_query = pd.read_sql_query("select * from example_table;", conn)
print(df_query.head(), '\n', df_query.shape)

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
 (145289, 8)

In [75]:
# insert dataframe into table. If table exist, it would replace it
df.to_sql("example_table", conn, if_exists="append", index=False)

145289

In [76]:
df_query = pd.read_sql_query("select * from example_table;", conn)
print(df_query.shape)

(290578, 8)

### Interacting with Databases

### drop existed table first

In [77]:
import sqlite3
query = """drop table test;"""
con = sqlite3.connect('./data/mydata.sqlite')
con.execute(query)
con.commit()

### create a table

In [78]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('./data/mydata.sqlite')
con.execute(query)
con.commit()

### empty db

In [80]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [81]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [82]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5),
 ('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [83]:
# import pandas as pd
# cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5
3      Atlanta     Georgia  1.25  6
4  Tallahassee     Florida  2.60  3
5   Sacramento  California  1.70  5

---
# Mod 13 連接、合併和重塑 Data Wrangling : Join, Combine
> * 能夠找到、檢索、清理、處理、分析和表示不同類型的資料。<br>
> * 在很多應用中，資料通常散落在不同的檔或資料庫中，並不方便進行分析, 基本上不脫離 ETL (Extraction, Transform, Loading) 的範疇
>> * reshape：整形
>> * merge：歸併
>> * concatenate：串聯
>> * pivot：旋轉
>> * stack：堆疊

pandas 提供了多種便捷的工具，可以輕鬆地將 Series 和 DataFrame 物件組合在一起，並支援各種集合邏輯（用於索引）和關係代數功能（用於連接/合併類型的操作）。

In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Merging Datasets
pd.merge()：像 SQL 一樣的關聯查詢
當你有兩個 DataFrame，且它們之間有共同的欄位（例如 ID 或 姓名），你想把相關資訊「合併」在一起時使用。
* 方向：水平合併（增加欄位）。
* 關鍵點：依據內容（Key）來對齊。
* 常見參數：on (基準欄位), how ('inner', 'outer', 'left', 'right')。

### Database-Style DataFrame Joins
><img src="./img/merge.jpg"  style='width:100%'>

><img src="./img/merge01.jpg"  style='width:100%'>
><img src="./img/merge02.png"  style='width:100%'>

Pandas `merge()` 的 `how` 參數，直接對應了 SQL 的各種 `JOIN` 類型：

| 功能 | SQL 語法 | Pandas `merge()` 語法 | 說明 |
|:---:|:---:|:---:|:---:|
| 內連接 | `INNER JOIN` | `df1.merge(df2, how='inner')` | 只保留兩邊都有配對成功的資料（**預設值**） |
| 左外連接 | `LEFT JOIN` | `df1.merge(df2, how='left')` | 保留左邊所有資料，右邊沒配對到的補 `NaN` |
| 右外連接 | `RIGHT JOIN` | `df1.merge(df2, how='right')` | 保留右邊所有資料，左邊沒配對到的補 `NaN` |
| 全外連接 | `FULL OUTER JOIN` | `df1.merge(df2, how='outer')` | 保留兩邊所有的資料，沒配對到的地方補 `NaN` |
| 交叉連接 | `CROSS JOIN` | `df1.merge(df2, how='cross')` | 產生笛卡爾積（每個左邊列配對所有右邊列） |

In [85]:
df1 = pd.DataFrame({'k1': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df2 = pd.DataFrame({'k1': ['a', 'b', 'd'], 'data2': range(3)})
df1, df2

(  k1  data1
 0  b      0
 1  b      1
 2  a      2
 3  c      3
 4  a      4
 5  a      5
 6  b      6,
   k1  data2
 0  a      0
 1  b      1
 2  d      2)

### 若未註明 on, 找到相同的 column 交集 (~ inner join)

In [86]:
df1, df2, pd.merge(df1, df2)  # 找到相同的 column 交集 shift-tab "on"

(  k1  data1
 0  b      0
 1  b      1
 2  a      2
 3  c      3
 4  a      4
 5  a      5
 6  b      6,
   k1  data2
 0  a      0
 1  b      1
 2  d      2,
   k1  data1  data2
 0  b      0      1
 1  b      1      1
 2  a      2      0
 3  a      4      0
 4  a      5      0
 5  b      6      1)

In [87]:
pd.merge(df1, df2, on='k1')  # column 'key' 相同

  k1  data1  data2
0  b      0      1
1  b      1      1
2  a      2      0
3  a      4      0
4  a      5      0
5  b      6      1

### 若未註明 on, 找到相同的 column 聯集 (~ outer / join) full

In [88]:
df1, df2, pd.merge(df1, df2, how='outer') # 聯集

(  k1  data1
 0  b      0
 1  b      1
 2  a      2
 3  c      3
 4  a      4
 5  a      5
 6  b      6,
   k1  data2
 0  a      0
 1  b      1
 2  d      2,
   k1  data1  data2
 0  a    2.0    0.0
 1  a    4.0    0.0
 2  a    5.0    0.0
 3  b    0.0    1.0
 4  b    1.0    1.0
 5  b    6.0    1.0
 6  c    3.0    NaN
 7  d    NaN    2.0)

In [89]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b','b', 'd'], 'data2': range(4)})
print(f'{df3}\n\n'
      f'{df4}\n\n'
      f"{pd.merge(df3, df4, how='outer', left_on='lkey', right_on='rkey')}")

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

  rkey  data2
0    a      0
1    b      1
2    b      2
3    d      3

   lkey  data1 rkey  data2
0     a    2.0    a    0.0
1     a    4.0    a    0.0
2     a    5.0    a    0.0
3     b    0.0    b    1.0
4     b    0.0    b    2.0
5     b    1.0    b    1.0
6     b    1.0    b    2.0
7     b    6.0    b    1.0
8     b    6.0    b    2.0
9     c    3.0  NaN    NaN
10  NaN    NaN    d    3.0

### column 左右聯結 (~ left / right join)

In [90]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})
print(f'{df1}\n\n'
      f'{df2}\n\n'
      f"left merger :\n{pd.merge(df1, df2, on='key', how='left')}\n\n"
      f"right merger :\n{pd.merge(df1, df2, on='key', how='right')}")

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

left merger :
   key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

right merger :
   key  data1  data2
0    a    2.0      0
1    a    4.0      0
2    b    0.0      1
3    b    1.0      1
4    b    5.0      1
5    a    2.0      2
6    a    4.0      2
7    b    0.0      3
8    b    1.0      3
9    b    5.0      3
10   d    NaN      4

### inner join = join

In [91]:
df1, df2, pd.merge(df1, df2, how='inner'), pd.merge(df1, df2)

(  key  data1
 0   b      0
 1   b      1
 2   a      2
 3   c      3
 4   a      4
 5   b      5,
   key  data2
 0   a      0
 1   b      1
 2   a      2
 3   b      3
 4   d      4,
   key  data1  data2
 0   b      0      1
 1   b      0      3
 2   b      1      1
 3   b      1      3
 4   a      2      0
 5   a      2      2
 6   a      4      0
 7   a      4      2
 8   b      5      1
 9   b      5      3,
   key  data1  data2
 0   b      0      1
 1   b      0      3
 2   b      1      1
 3   b      1      3
 4   a      2      0
 5   a      2      2
 6   a      4      0
 7   a      4      2
 8   b      5      1
 9   b      5      3)

In [92]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
print(f'{left}\n\n'
      f'{right}\n\n'
      f"{pd.merge(left, right, on=['key1', 'key2'], how='outer')}")

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

  key1 key2  lval  rval
0  bar  one   3.0   6.0
1  bar  two   NaN   7.0
2  foo  one   1.0   4.0
3  foo  one   1.0   5.0
4  foo  two   2.0   NaN

In [93]:
print(f"{pd.merge(left, right, on='key1')}\n\n"
      f"{pd.merge(left, right, on='key1', suffixes=('_left', '_right'))}")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

## Concatenating Along an Axis
> concat() 確實也有 join='inner' 和 join='outer' 參數。雖然 merge() 和 concat() 都有這兩個詞，但它們對齊的對象完全不同

> 關鍵點：`依據軸（Index 或 Column 名稱）來拼接`，`不考慮欄位內容的邏輯關聯`
> * pd.concat()：它的 Key 就是 Index（索引）`預設` 或 Column Name（欄位名）。它是根據「標籤名稱」在對齊。
> * pd.merge()：它的 Key 是 Data Values（資料內容）。它是根據「格子裡的數值」在對齊。

In [94]:
arr = np.arange(12).reshape((3, 4))
arr, np.concatenate([arr, arr]), np.concatenate([arr, arr], axis=1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]]))

### Series concat

In [95]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['b', 'c', 'd'])
s3 = pd.Series([5, 6], index=['d', 'e'])

print(f'{s1}\n\n'
      f'{s2}\n\n'
      f'{s3}\n\n'
      f'{pd.concat([s1, s2, s3])}')  # default axis = 0

a    0
b    1
dtype: int64

b    2
c    3
d    4
dtype: int64

d    5
e    6
dtype: int64

a    0
b    1
b    2
c    3
d    4
d    5
e    6
dtype: int64

In [96]:
s1, s2, s3, pd.concat([s1, s2, s3], axis=1, join='outer')   # try inner

(a    0
 b    1
 dtype: int64,
 b    2
 c    3
 d    4
 dtype: int64,
 d    5
 e    6
 dtype: int64,
      0    1    2
 a  0.0  NaN  NaN
 b  1.0  2.0  NaN
 c  NaN  3.0  NaN
 d  NaN  4.0  5.0
 e  NaN  NaN  6.0)

In [100]:
s4 = pd.concat([s1, s3])
print(f'{s1}\n\n'
      f'{s4}\n\n'
      f'{pd.concat([s1, s4], axis=1)}\n\n'
      f"{pd.concat([s1, s4], axis=1, join='inner')}")

a    0
b    1
dtype: int64

a    0
b    1
d    5
e    6
dtype: int64

     0  1
a  0.0  0
b  1.0  1
d  NaN  5
e  NaN  6

   0  1
a  0  0
b  1  1

In [101]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(f'{df1}\n\n'
      f'{df2}')

          a         b         c         d
0 -0.364173 -1.008681  1.603678  0.288851
1  1.437700  1.014436 -0.240080 -1.163984
2 -1.489864  1.043732 -1.152037  1.414555

          b        d         a
0  2.236654  0.34955 -0.394617
1 -0.787780  1.19427  0.750861

In [102]:
pd.concat([df1, df2], ignore_index=False, join='outer', axis=0)

          a         b         c         d
0 -0.364173 -1.008681  1.603678  0.288851
1  1.437700  1.014436 -0.240080 -1.163984
2 -1.489864  1.043732 -1.152037  1.414555
0 -0.394617  2.236654       NaN  0.349550
1  0.750861 -0.787780       NaN  1.194270

In [103]:
pd.concat([df1, df2], ignore_index=False, join='inner', axis=0)

          a         b         d
0 -0.364173 -1.008681  0.288851
1  1.437700  1.014436 -1.163984
2 -1.489864  1.043732  1.414555
0 -0.394617  2.236654  0.349550
1  0.750861 -0.787780  1.194270

In [104]:
pd.concat([df1, df2], ignore_index=False, join='inner', axis=1)

          a         b         c         d         b        d         a
0 -0.364173 -1.008681  1.603678  0.288851  2.236654  0.34955 -0.394617
1  1.437700  1.014436 -0.240080 -1.163984 -0.787780  1.19427  0.750861

In [105]:
pd.concat([df1, df2], ignore_index=False, join='outer', axis=1)

          a         b         c         d         b        d         a
0 -0.364173 -1.008681  1.603678  0.288851  2.236654  0.34955 -0.394617
1  1.437700  1.014436 -0.240080 -1.163984 -0.787780  1.19427  0.750861
2 -1.489864  1.043732 -1.152037  1.414555       NaN      NaN       NaN

# `練習 Q02 (9,10)`

---
<center><h1>--- The End ---</h1><center>